name: Validate LinkML Schema

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install linkml

      - name: Run LinkML validation
        run: |
          linkml-validate --schema code/linkml/journals.yaml journals.yaml
